In [18]:
import pandas as pd
import torch
from transformers import AutoModelForSequenceClassification, AutoTokenizer
import ast
import numpy as np

In [19]:

# Load data
bt_sentences = pd.read_csv("C:/Users/rober/UCD/pol42050/new-sound-of-politics/data/bt_sentences_test.csv", index_col=False)
# len(bt_speeches["Speech"])
# bt_speeches20 = bt_speeches[bt_speeches["Period"] == 20]
# bt_speeches20.to_csv("C:/Users/rober/UCD/pol42050/new-sound-of-politics/data/bundestag_sentences20.csv")
bt_sentences

C:\Users\rober\AppData\Local\Temp\ipykernel_29036\911310729.py:2: DtypeWarning: Columns (0: Name) have mixed types. Specify dtype option on import or set low_memory=False.
  bt_sentences = pd.read_csv("C:/Users/rober/UCD/pol42050/new-sound-of-politics/data/bt_sentences_test.csv", index_col=False)

,speech_id,sentence_position,sentence,MPID,Date,Chair,Session,Period,Party,Name
0,207,1,Herr Präsident!,17826,2022-01-14,False,12,20,['afd'],Albrecht Glaser
1,207,2,Meine sehr verehrten Damen und Herren!,17826,2022-01-14,False,12,20,['afd'],Albrecht Glaser
2,207,3,Mehr Fortschritt soll es im Lande geben.,17826,2022-01-14,False,12,20,['afd'],Albrecht Glaser
3,207,4,"Was ist das, und wie soll das gehen?",17826,2022-01-14,False,12,20,['afd'],Albrecht Glaser
4,208,1,"Herzlichen Dank, Frau Präsidentin.",17826,2022-01-27,True,14,20,['afd'],Albrecht Glaser
...,...,...,...,...,...,...,...,...,...,...
79047,57040,1,Herr Präsident!,21903,2023-04-19,True,96,20,['linke/pds/sed'],NaN
79048,57040,2,Meine Damen und Herren!,21903,2023-04-19,True,96,20,['linke/pds/sed'],NaN
79049,57040,3,Ein historischer Tag,21903,2023-04-19,True,96,20,['linke/pds/sed'],NaN
79050,57041,1,"Wie begründet die Bundesregierung, dass Entgel...",21904,2023-01-25,False,81,20,['cdu'],NaN
79051,57041,2,Aber ich habe hier eine andere Reihenfolge der...,21904,2023-01-25,False,81,20,['cdu'],NaN

In [20]:
# bt_speeches = bt_speeches.sample(frac=0.001)

# bt_speeches['Speech'] = bt_speeches['Speech'].apply(ast.literal_eval)

In [21]:
# Load model and tokenizer
tokenizer = AutoTokenizer.from_pretrained("luerhard/PopBERT")
model = AutoModelForSequenceClassification.from_pretrained("luerhard/PopBERT")

# CPU inference only
device = torch.device("cpu")
model = model.to(device)
model.eval()

Loading weights: 100%|██████████| 393/393 [00:00<00:00, 4469.68it/s]

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(31102, 1024, padding_idx=0)
      (position_embeddings): Embedding(512, 1024)
      (token_type_embeddings): Embedding(2, 1024)
      (LayerNorm): LayerNorm((1024,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-23): 24 x BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=1024, out_features=1024, bias=True)
              (key): Linear(in_features=1024, out_features=1024, bias=True)
              (value): Linear(in_features=1024, out_features=1024, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=1024, out_features=1024, bias=True)
              (LayerNorm): LayerNorm((1024,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=1024, out_features=4096, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=4096, out_features=1024, bias=True)
            (LayerNorm): LayerNorm((1024,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): BertPooler(
      (dense): Linear(in_features=1024, out_features=1024, bias=True)
      (activation): Tanh()
    )
  )
  (dropout): Dropout(p=0.1, inplace=False)
  (classifier): Linear(in_features=1024, out_features=4, bias=True)
)

In [22]:

# Optional: let PyTorch use available CPU threads
# Try 4 first, then 6 or 8 and benchmark on your machine
torch.set_num_threads(6)

# Dynamic INT8 quantization for linear layers
quantized_model = torch.quantization.quantize_dynamic(
    model,
    {torch.nn.Linear},
    dtype=torch.qint8
)
quantized_model.eval()

C:\Users\rober\AppData\Local\Temp\ipykernel_29036\3820193431.py:6: DeprecationWarning: torch.ao.quantization is deprecated and will be removed in 2.10.
For migrations of users:
1. Eager mode quantization (torch.ao.quantization.quantize, torch.ao.quantization.quantize_dynamic), please migrate to use torchao eager mode quantize_ API instead
2. FX graph mode quantization (torch.ao.quantization.quantize_fx.prepare_fx,torch.ao.quantization.quantize_fx.convert_fx, please migrate to use torchao pt2e quantization API instead (prepare_pt2e, convert_pt2e)
3. pt2e quantization has been migrated to torchao (https://github.com/pytorch/ao/tree/main/torchao/quantization/pt2e)
see https://github.com/pytorch/ao/issues/2259 for more details
  quantized_model = torch.quantization.quantize_dynamic(

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(31102, 1024, padding_idx=0)
      (position_embeddings): Embedding(512, 1024)
      (token_type_embeddings): Embedding(2, 1024)
      (LayerNorm): LayerNorm((1024,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-23): 24 x BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): DynamicQuantizedLinear(in_features=1024, out_features=1024, dtype=torch.qint8, qscheme=torch.per_tensor_affine)
              (key): DynamicQuantizedLinear(in_features=1024, out_features=1024, dtype=torch.qint8, qscheme=torch.per_tensor_affine)
              (value): DynamicQuantizedLinear(in_features=1024, out_features=1024, dtype=torch.qint8, qscheme=torch.per_tensor_affine)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): DynamicQuantizedLinear(in_features=1024, out_features=1024, dtype=torch.qint8, qscheme=torch.per_tensor_affine)
              (LayerNorm): LayerNorm((1024,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): DynamicQuantizedLinear(in_features=1024, out_features=4096, dtype=torch.qint8, qscheme=torch.per_tensor_affine)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): DynamicQuantizedLinear(in_features=4096, out_features=1024, dtype=torch.qint8, qscheme=torch.per_tensor_affine)
            (LayerNorm): LayerNorm((1024,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): BertPooler(
      (dense): DynamicQuantizedLinear(in_features=1024, out_features=1024, dtype=torch.qint8, qscheme=torch.per_tensor_affine)
      (activation): Tanh()
    )
  )
  (dropout): Dropout(p=0.1, inplace=False)
  (classifier): DynamicQuantizedLinear(in_features=1024, out_features=4, dtype=torch.qint8, qscheme=torch.per_tensor_affine)
)

In [46]:
subset = bt_sentences.iloc[0:50]

sentence_scores = []
for i, sentence in enumerate(subset["sentence"]):
    print(f"analysing sentence {i+1}")
    
    encodings = tokenizer(
        sentence,
        return_tensors="pt",
        padding=True,
        truncation=True
    )

    encodings = {k: v.to(device) for k, v in encodings.items()}

    with torch.inference_mode():
        out = quantized_model(**encodings)

    probs = torch.sigmoid(out.logits)
    sentence_scores.append(
        [bt_sentences.at[subset.index[i], "speech_id"], 
        bt_sentences.at[subset.index[i], "sentence_position"]] + 
        probs.cpu().numpy()[0].tolist()
    )

analysing sentence 1
analysing sentence 2
analysing sentence 3
analysing sentence 4
analysing sentence 5
analysing sentence 6
analysing sentence 7
analysing sentence 8
analysing sentence 9
analysing sentence 10
analysing sentence 11
analysing sentence 12
analysing sentence 13
analysing sentence 14
analysing sentence 15
analysing sentence 16
analysing sentence 17
analysing sentence 18
analysing sentence 19
analysing sentence 20
analysing sentence 21
analysing sentence 22
analysing sentence 23
analysing sentence 24
analysing sentence 25
analysing sentence 26
analysing sentence 27
analysing sentence 28
analysing sentence 29
analysing sentence 30
analysing sentence 31
analysing sentence 32
analysing sentence 33
analysing sentence 34
analysing sentence 35
analysing sentence 36
analysing sentence 37
analysing sentence 38
analysing sentence 39
analysing sentence 40
analysing sentence 41
analysing sentence 42
analysing sentence 43
analysing sentence 44
analysing sentence 45
analysing sentence 46
analysing sentence 47
analysing sentence 48
analysing sentence 49
analysing sentence 50

In [49]:
subset["scores"] = sentence_scores

In [50]:

# Create DataFrame with custom column names
scores_df = pd.DataFrame(sentence_scores, columns=['speech_id', 'sentence_position', 'Anti-Elitism', 'People-Centrism', 'Left-Wing Host-Ideology', 'Right-Wing Host-Ideology'])

In [51]:
scores_df

,speech_id,sentence_position,Anti-Elitism,People-Centrism,Left-Wing Host-Ideology,Right-Wing Host-Ideology
0,207,1,0.133563,0.079781,0.057177,0.071662
1,207,2,0.142408,0.080203,0.056765,0.067925
2,207,3,0.179715,0.136445,0.084267,0.174430
3,207,4,0.121376,0.082099,0.059250,0.081766
4,208,1,0.142205,0.099597,0.075766,0.077304
5,208,2,0.200162,0.114274,0.078428,0.098393
6,209,1,0.153239,0.097394,0.064412,0.088444
7,209,2,0.116895,0.068606,0.054694,0.067936
8,210,1,0.133563,0.079781,0.057177,0.071662
9,210,2,0.149257,0.071118,0.064535,0.069349
10,210,3,0.151097,0.069116,0.062389,0.069242
11,211,1,0.159004,0.086150,0.080210,0.072853
12,211,2,0.149257,0.071118,0.064535,0.069349
13,211,3,0.147873,0.120304,0.061092,0.074344
14,211,4,0.145131,0.094343,0.047389,0.066069
15,212,1,0.159004,0.086150,0.080210,0.072853
16,212,2,0.149257,0.071118,0.064535,0.069349
17,212,3,0.103765,0.109734,0.056107,0.057584
18,212,4,0.115119,0.086378,0.037274,0.048462
19,213,1,0.159004,0.086150,0.080210,0.072853
20,213,2,0.149257,0.071118,0.064535,0.069349
21,213,3,0.178262,0.088414,0.076153,0.077506
22,213,4,0.136116,0.092037,0.072509,0.106693
23,213,5,0.175498,0.081085,0.048670,0.074727
24,214,1,0.159004,0.086150,0.080210,0.072853
25,214,2,0.142408,0.080203,0.056765,0.067925
26,214,3,0.117824,0.086231,0.088548,0.085817
27,214,4,0.131476,0.088400,0.058738,0.079650
28,214,5,0.131110,0.132583,0.093500,0.127377
29,215,1,0.159004,0.086150,0.080210,0.072853
30,215,2,0.149257,0.071118,0.064535,0.069349
31,215,3,0.213779,0.076094,0.050826,0.079327
32,215,4,0.185372,0.112856,0.074874,0.079621
33,215,5,0.198189,0.129528,0.108332,0.115102
34,215,6,0.175201,0.074723,0.076666,0.083127
35,215,7,0.134849,0.109040,0.064154,0.083933
36,215,8,0.176801,0.103446,0.074613,0.116107
37,215,9,0.099335,0.066429,0.038452,0.051546
38,215,10,0.158400,0.098274,0.054798,0.089898
39,215,11,0.100980,0.075658,0.037019,0.041607
40,215,12,0.123571,0.117437,0.072042,0.085861
41,215,13,0.149530,0.113495,0.069356,0.083455
42,216,1,0.159004,0.086150,0.080210,0.072853
43,216,2,0.149257,0.071118,0.064535,0.069349
44,216,3,0.170355,0.081458,0.065569,0.079083
45,217,1,0.133563,0.079781,0.057177,0.071662
46,217,2,0.142408,0.080203,0.056765,0.067925
47,217,3,0.122192,0.121028,0.081097,0.098236
48,218,1,0.159004,0.086150,0.080210,0.072853
49,218,2,0.149257,0.071118,0.064535,0.069349