In [1]:
import pandas as pd
import torch
from transformers import AutoModelForSequenceClassification, AutoTokenizer
import ast
import numpy as np

c:\Users\rober\UCD\pol42050\new-sound-of-politics\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [22]:

# Load data
bt_sentences = pd.read_csv("C:/Users/rober/UCD/pol42050/new-sound-of-politics/data/bundestag_sentences20.csv", index_col=False)
# len(bt_speeches["Speech"])
# bt_speeches20 = bt_speeches[bt_speeches["Period"] == 20]
# bt_speeches20.to_csv("C:/Users/rober/UCD/pol42050/new-sound-of-politics/data/bundestag_sentences20.csv")
bt_sentences.head()

,speech_id,sentence_position,sentence,MPID,Date,Chair,Session,Period,Party,Name
0,0,1,Herr Präsident!,17826,2022-01-14,False,12,20,['afd'],Albrecht Glaser
1,0,2,Meine sehr verehrten Damen und Herren!,17826,2022-01-14,False,12,20,['afd'],Albrecht Glaser
2,0,3,Mehr Fortschritt soll es im Lande geben.,17826,2022-01-14,False,12,20,['afd'],Albrecht Glaser
3,0,4,"Was ist das, und wie soll das gehen?",17826,2022-01-14,False,12,20,['afd'],Albrecht Glaser
4,1,1,"Sehr geehrter Herr Dr. Hahn, ich versichere, d...",17826,2022-01-28,False,15,20,['afd'],Albrecht Glaser

In [23]:
# bt_speeches = bt_speeches.sample(frac=0.001)

# bt_speeches['Speech'] = bt_speeches['Speech'].apply(ast.literal_eval)

In [24]:
# Load model and tokenizer
tokenizer = AutoTokenizer.from_pretrained("luerhard/PopBERT")
model = AutoModelForSequenceClassification.from_pretrained("luerhard/PopBERT")

# CPU inference only
device = torch.device("cpu")
model = model.to(device)
model.eval()

Loading weights: 100%|██████████| 393/393 [00:00<00:00, 4431.96it/s]

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(31102, 1024, padding_idx=0)
      (position_embeddings): Embedding(512, 1024)
      (token_type_embeddings): Embedding(2, 1024)
      (LayerNorm): LayerNorm((1024,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-23): 24 x BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=1024, out_features=1024, bias=True)
              (key): Linear(in_features=1024, out_features=1024, bias=True)
              (value): Linear(in_features=1024, out_features=1024, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=1024, out_features=1024, bias=True)
              (LayerNorm): LayerNorm((1024,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=1024, out_features=4096, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=4096, out_features=1024, bias=True)
            (LayerNorm): LayerNorm((1024,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): BertPooler(
      (dense): Linear(in_features=1024, out_features=1024, bias=True)
      (activation): Tanh()
    )
  )
  (dropout): Dropout(p=0.1, inplace=False)
  (classifier): Linear(in_features=1024, out_features=4, bias=True)
)

In [25]:

# Optional: let PyTorch use available CPU threads
# Try 4 first, then 6 or 8 and benchmark on your machine
torch.set_num_threads(6)

# Dynamic INT8 quantization for linear layers
quantized_model = torch.quantization.quantize_dynamic(
    model,
    {torch.nn.Linear},
    dtype=torch.qint8
)
quantized_model.eval()

C:\Users\rober\AppData\Local\Temp\ipykernel_18832\3820193431.py:6: DeprecationWarning: torch.ao.quantization is deprecated and will be removed in 2.10.
For migrations of users:
1. Eager mode quantization (torch.ao.quantization.quantize, torch.ao.quantization.quantize_dynamic), please migrate to use torchao eager mode quantize_ API instead
2. FX graph mode quantization (torch.ao.quantization.quantize_fx.prepare_fx,torch.ao.quantization.quantize_fx.convert_fx, please migrate to use torchao pt2e quantization API instead (prepare_pt2e, convert_pt2e)
3. pt2e quantization has been migrated to torchao (https://github.com/pytorch/ao/tree/main/torchao/quantization/pt2e)
see https://github.com/pytorch/ao/issues/2259 for more details
  quantized_model = torch.quantization.quantize_dynamic(

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(31102, 1024, padding_idx=0)
      (position_embeddings): Embedding(512, 1024)
      (token_type_embeddings): Embedding(2, 1024)
      (LayerNorm): LayerNorm((1024,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-23): 24 x BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): DynamicQuantizedLinear(in_features=1024, out_features=1024, dtype=torch.qint8, qscheme=torch.per_tensor_affine)
              (key): DynamicQuantizedLinear(in_features=1024, out_features=1024, dtype=torch.qint8, qscheme=torch.per_tensor_affine)
              (value): DynamicQuantizedLinear(in_features=1024, out_features=1024, dtype=torch.qint8, qscheme=torch.per_tensor_affine)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): DynamicQuantizedLinear(in_features=1024, out_features=1024, dtype=torch.qint8, qscheme=torch.per_tensor_affine)
              (LayerNorm): LayerNorm((1024,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): DynamicQuantizedLinear(in_features=1024, out_features=4096, dtype=torch.qint8, qscheme=torch.per_tensor_affine)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): DynamicQuantizedLinear(in_features=4096, out_features=1024, dtype=torch.qint8, qscheme=torch.per_tensor_affine)
            (LayerNorm): LayerNorm((1024,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): BertPooler(
      (dense): DynamicQuantizedLinear(in_features=1024, out_features=1024, dtype=torch.qint8, qscheme=torch.per_tensor_affine)
      (activation): Tanh()
    )
  )
  (dropout): Dropout(p=0.1, inplace=False)
  (classifier): DynamicQuantizedLinear(in_features=1024, out_features=4, dtype=torch.qint8, qscheme=torch.per_tensor_affine)
)

In [26]:
len(bt_sentences["sentence"])

44501

In [27]:
subset = bt_sentences  # Process only the first 1000 sentences for testing

sentence_scores = []
for i, sentence in enumerate(subset["sentence"]):
    print(f"analysing sentence {i+1}")
    
    encodings = tokenizer(
        sentence,
        return_tensors="pt",
        padding=True,
        truncation=True
    )

    encodings = {k: v.to(device) for k, v in encodings.items()}

    with torch.inference_mode():
        out = quantized_model(**encodings)

    probs = torch.sigmoid(out.logits)
    sentence_scores.append(
        [bt_sentences.at[subset.index[i], "speech_id"], 
        bt_sentences.at[subset.index[i], "sentence_position"]] + 
        probs.cpu().numpy()[0].tolist()
    )

analysing sentence 1
analysing sentence 2
analysing sentence 3
analysing sentence 4
analysing sentence 5
analysing sentence 6
analysing sentence 7
analysing sentence 8
analysing sentence 9
analysing sentence 10
analysing sentence 11
analysing sentence 12
analysing sentence 13
analysing sentence 14
analysing sentence 15
analysing sentence 16
analysing sentence 17
analysing sentence 18
analysing sentence 19
analysing sentence 20
analysing sentence 21
analysing sentence 22
analysing sentence 23
analysing sentence 24
analysing sentence 25
analysing sentence 26
analysing sentence 27
analysing sentence 28
analysing sentence 29
analysing sentence 30
analysing sentence 31
analysing sentence 32
analysing sentence 33
analysing sentence 34
analysing sentence 35
analysing sentence 36
analysing sentence 37
analysing sentence 38
analysing sentence 39
analysing sentence 40
analysing sentence 41
analysing sentence 42
analysing sentence 43
analysing sentence 44
analysing sentence 45
analysing sentence 46
analysing sentence 47
analysing sentence 48
analysing sentence 49
analysing sentence 50
analysing sentence 51
analysing sentence 52
analysing sentence 53
analysing sentence 54
analysing sentence 55
analysing sentence 56
analysing sentence 57
analysing sentence 58
analysing sentence 59
analysing sentence 60
analysing sentence 61
analysing sentence 62
analysing sentence 63
analysing sentence 64
analysing sentence 65
analysing sentence 66
analysing sentence 67
analysing sentence 68
analysing sentence 69
analysing sentence 70
analysing sentence 71
analysing sentence 72
analysing sentence 73
analysing sentence 74
analysing sentence 75
analysing sentence 76
analysing sentence 77
analysing sentence 78
analysing sentence 79
analysing sentence 80
analysing sentence 81
analysing sentence 82
analysing sentence 83
analysing sentence 84
analysing sentence 85
analysing sentence 86
analysing sentence 87
analysing sentence 88
analysing sentence 89
analysing sentence 90
analysing sentence 91
analysing sentence 92
analysing sentence 93
analysing sentence 94
analysing sentence 95
analysing sentence 96
analysing sentence 97
analysing sentence 98
analysing sentence 99
analysing sentence 100
analysing sentence 101
analysing sentence 102
analysing sentence 103
analysing sentence 104
analysing sentence 105
analysing sentence 106
analysing sentence 107
analysing sentence 108
analysing sentence 109
analysing sentence 110
analysing sentence 111
analysing sentence 112
analysing sentence 113
analysing sentence 114
analysing sentence 115
analysing sentence 116
analysing sentence 117
analysing sentence 118
analysing sentence 119
analysing sentence 120
analysing sentence 121
analysing sentence 122
analysing sentence 123
analysing sentence 124
analysing sentence 125
analysing sentence 126
analysing sentence 127
analysing sentence 128
analysing sentence 129
analysing sentence 130
analysing sentence 131
analysing sentence 132
analysing sentence 133
analysing sentence 134
analysing sentence 135
analysing sentence 136
analysing sentence 137
analysing sentence 138
analysing sentence 139
analysing sentence 140
analysing sentence 141
analysing sentence 142
analysing sentence 143
analysing sentence 144
analysing sentence 145
analysing sentence 146
analysing sentence 147
analysing sentence 148
analysing sentence 149
analysing sentence 150
analysing sentence 151
analysing sentence 152
analysing sentence 153
analysing sentence 154
analysing sentence 155
analysing sentence 156
analysing sentence 157
analysing sentence 158
analysing sentence 159
analysing sentence 160
analysing sentence 161
analysing sentence 162
analysing sentence 163
analysing sentence 164
analysing sentence 165
analysing sentence 166
analysing sentence 167
analysing sentence 168
analysing sentence 169
analysing sentence 170
analysing sentence 171
analysing sentence 172
analysing sentence 173
analysing sentence 174
analysing sentence 175
analysing sentence 176
analysing sentence 177
analysing sentence 178
analysing sentence 179
analysing sentence 180
analysing sentence 181
analysing sentence 182
analysing sentence 183
analysing sentence 184
analysing sentence 185
analysing sentence 186
analysing sentence 187
analysing sentence 188
analysing sentence 189
analysing sentence 190
analysing sentence 191
analysing sentence 192
analysing sentence 193
analysing sentence 194
analysing sentence 195
analysing sentence 196
analysing sentence 197
analysing sentence 198
analysing sentence 199
analysing sentence 200
analysing sentence 201
analysing sentence 202
analysing sentence 203
analysing sentence 204
analysing sentence 205
analysing sentence 206
analysing sentence 207
analysing sentence 208
analysing sentence 209
analysing sentence 210
analysing sentence 211
analysing sentence 212
analysing sentence 213
analysing sentence 214
analysing sentence 215
analysing sentence 216
analysing sentence 217
analysing sentence 218
analysing sentence 219
analysing sentence 220
analysing sentence 221
analysing sentence 222
analysing sentence 223
analysing sentence 224
analysing sentence 225
analysing sentence 226
analysing sentence 227
analysing sentence 228
analysing sentence 229
analysing sentence 230
analysing sentence 231
analysing sentence 232
analysing sentence 233
analysing sentence 234
analysing sentence 235
analysing sentence 236
analysing sentence 237
analysing sentence 238
analysing sentence 239
analysing sentence 240
analysing sentence 241
analysing sentence 242
analysing sentence 243
analysing sentence 244
analysing sentence 245
analysing sentence 246
analysing sentence 247
analysing sentence 248
analysing sentence 249
analysing sentence 250
analysing sentence 251
analysing sentence 252
analysing sentence 253
analysing sentence 254
analysing sentence 255
analysing sentence 256
analysing sentence 257
analysing sentence 258
analysing sentence 259
analysing sentence 260
analysing sentence 261
analysing sentence 262
analysing sentence 263
analysing sentence 264
analysing sentence 265
analysing sentence 266
analysing sentence 267
analysing sentence 268
analysing sentence 269
analysing sentence 270
analysing sentence 271
analysing sentence 272
analysing sentence 273
analysing sentence 274
analysing sentence 275
analysing sentence 276
analysing sentence 277
analysing sentence 278
analysing sentence 279
analysing sentence 280
analysing sentence 281
analysing sentence 282
analysing sentence 283
analysing sentence 284
analysing sentence 285
analysing sentence 286
analysing sentence 287
analysing sentence 288
analysing sentence 289
analysing sentence 290
analysing sentence 291
analysing sentence 292
analysing sentence 293
analysing sentence 294
analysing sentence 295
analysing sentence 296
analysing sentence 297
analysing sentence 298
analysing sentence 299
analysing sentence 300
analysing sentence 301
analysing sentence 302
analysing sentence 303
analysing sentence 304
analysing sentence 305
analysing sentence 306
analysing sentence 307
analysing sentence 308
analysing sentence 309
analysing sentence 310
analysing sentence 311
analysing sentence 312
analysing sentence 313
analysing sentence 314
analysing sentence 315
analysing sentence 316
analysing sentence 317
analysing sentence 318
analysing sentence 319
analysing sentence 320
analysing sentence 321
analysing sentence 322
analysing sentence 323
analysing sentence 324
analysing sentence 325
analysing sentence 326
analysing sentence 327
analysing sentence 328
analysing sentence 329
analysing sentence 330
analysing sentence 331
analysing sentence 332
analysing sentence 333
analysing sentence 334
analysing sentence 335
analysing sentence 336
analysing sentence 337
analysing sentence 338
analysing sentence 339
analysing sentence 340
analysing sentence 341
analysing sentence 342
analysing sentence 343
analysing sentence 344
analysing sentence 345
analysing sentence 346
analysing sentence 347
analysing sentence 348
analysing sentence 349
analysing sentence 350
analysing sentence 351
analysing sentence 352
analysing sentence 353
analysing sentence 354
analysing sentence 355
analysing sentence 356
analysing sentence 357
analysing sentence 358
analysing sentence 359
analysing sentence 360
analysing sentence 361
analysing sentence 362
analysing sentence 363
analysing sentence 364
analysing sentence 365
analysing sentence 366
analysing sentence 367
analysing sentence 368
analysing sentence 369
analysing sentence 370
analysing sentence 371
analysing sentence 372
analysing sentence 373
analysing sentence 374
analysing sentence 375
analysing sentence 376
analysing sentence 377
analysing sentence 378
analysing sentence 379
analysing sentence 380
analysing sentence 381
analysing sentence 382
analysing sentence 383
analysing sentence 384
analysing sentence 385
analysing sentence 386
analysing sentence 387
analysing sentence 388
analysing sentence 389
analysing sentence 390
analysing sentence 391
analysing sentence 392
analysing sentence 393
analysing sentence 394
analysing sentence 395
analysing sentence 396
analysing sentence 397
analysing sentence 398
analysing sentence 399
analysing sentence 400
analysing sentence 401
analysing sentence 402
analysing sentence 403
analysing sentence 404
analysing sentence 405
analysing sentence 406
analysing sentence 407
analysing sentence 408
analysing sentence 409
analysing sentence 410
analysing sentence 411
analysing sentence 412
analysing sentence 413
analysing sentence 414
analysing sentence 415
analysing sentence 416
analysing sentence 417
analysing sentence 418
analysing sentence 419
analysing sentence 420
analysing sentence 421
analysing sentence 422
analysing sentence 423
analysing sentence 424
analysing sentence 425
analysing sentence 426
analysing sentence 427
analysing sentence 428
analysing sentence 429
analysing sentence 430
analysing sentence 431
analysing sentence 432
analysing sentence 433
analysing sentence 434
analysing sentence 435
analysing sentence 436
analysing sentence 437
analysing sentence 438
analysing sentence 439
analysing sentence 440
analysing sentence 441
analysing sentence 442
analysing sentence 443
analysing sentence 444
analysing sentence 445
analysing sentence 446
analysing sentence 447
analysing sentence 448
analysing sentence 449
analysing sentence 450
analysing sentence 451
analysing sentence 452
analysing sentence 453
analysing sentence 454
analysing sentence 455
analysing sentence 456
analysing sentence 457
analysing sentence 458
analysing sentence 459
analysing sentence 460
analysing sentence 461
analysing sentence 462
analysing sentence 463
analysing sentence 464
analysing sentence 465
analysing sentence 466
analysing sentence 467
analysing sentence 468
analysing sentence 469
analysing sentence 470
analysing sentence 471
analysing sentence 472
analysing sentence 473
analysing sentence 474
analysing sentence 475
analysing sentence 476
analysing sentence 477
analysing sentence 478
analysing sentence 479
analysing sentence 480
analysing sentence 481
analysing sentence 482
analysing sentence 483
analysing sentence 484
analysing sentence 485
analysing sentence 486
analysing sentence 487
analysing sentence 488
analysing sentence 489
analysing sentence 490
analysing sentence 491
analysing sentence 492
analysing sentence 493
analysing sentence 494
analysing sentence 495
analysing sentence 496
analysing sentence 497
analysing sentence 498
analysing sentence 499
analysing sentence 500
analysing sentence 501
analysing sentence 502
analysing sentence 503
analysing sentence 504
analysing sentence 505
analysing sentence 506
analysing sentence 507
analysing sentence 508
analysing sentence 509
analysing sentence 510
analysing sentence 511
analysing sentence 512
analysing sentence 513
analysing sentence 514
analysing sentence 515
analysing sentence 516
analysing sentence 517
analysing sentence 518
analysing sentence 519
analysing sentence 520
analysing sentence 521
analysing sentence 522
analysing sentence 523
analysing sentence 524
analysing sentence 525
analysing sentence 526
analysing sentence 527
analysing sentence 528
analysing sentence 529
analysing sentence 530
analysing sentence 531
analysing sentence 532
analysing sentence 533
analysing sentence 534
analysing sentence 535
analysing sentence 536
analysing sentence 537
analysing sentence 538
analysing sentence 539
analysing sentence 540
analysing sentence 541
analysing sentence 542
analysing sentence 543
analysing sentence 544
analysing sentence 545
analysing sentence 546
analysing sentence 547
analysing sentence 548
analysing sentence 549
analysing sentence 550
analysing sentence 551
analysing sentence 552
analysing sentence 553
analysing sentence 554
analysing sentence 555
analysing sentence 556
analysing sentence 557
analysing sentence 558
analysing sentence 559
analysing sentence 560
analysing sentence 561
analysing sentence 562
analysing sentence 563
analysing sentence 564
analysing sentence 565
analysing sentence 566
analysing sentence 567
analysing sentence 568
analysing sentence 569
analysing sentence 570
analysing sentence 571
analysing sentence 572
analysing sentence 573
analysing sentence 574
analysing sentence 575
analysing sentence 576
analysing sentence 577
analysing sentence 578
analysing sentence 579
analysing sentence 580
analysing sentence 581
analysing sentence 582
analysing sentence 583
analysing sentence 584
analysing sentence 585
analysing sentence 586
analysing sentence 587
analysing sentence 588
analysing sentence 589
analysing sentence 590
analysing sentence 591
analysing sentence 592
analysing sentence 593
analysing sentence 594
analysing sentence 595
analysing sentence 596
analysing sentence 597
analysing sentence 598
analysing sentence 599
analysing sentence 600
analysing sentence 601
analysing sentence 602
analysing sentence 603
analysing sentence 604
analysing sentence 605
analysing sentence 606
analysing sentence 607
analysing sentence 608
analysing sentence 609
analysing sentence 610
analysing sentence 611
analysing sentence 612
analysing sentence 613
analysing sentence 614
analysing sentence 615
analysing sentence 616
analysing sentence 617
analysing sentence 618
analysing sentence 619
analysing sentence 620
analysing sentence 621
analysing sentence 622
analysing sentence 623
analysing sentence 624
analysing sentence 625
analysing sentence 626
analysing sentence 627
analysing sentence 628
analysing sentence 629
analysing sentence 630
analysing sentence 631
analysing sentence 632
analysing sentence 633
analysing sentence 634
analysing sentence 635
analysing sentence 636
analysing sentence 637
analysing sentence 638
analysing sentence 639
analysing sentence 640
analysing sentence 641
analysing sentence 642
analysing sentence 643
analysing sentence 644
analysing sentence 645
analysing sentence 646
analysing sentence 647
analysing sentence 648
analysing sentence 649
analysing sentence 650
analysing sentence 651
analysing sentence 652
analysing sentence 653
analysing sentence 654
analysing sentence 655
analysing sentence 656
analysing sentence 657
analysing sentence 658
analysing sentence 659
analysing sentence 660
analysing sentence 661
analysing sentence 662
analysing sentence 663
analysing sentence 664
analysing sentence 665
analysing sentence 666
analysing sentence 667
analysing sentence 668
analysing sentence 669
analysing sentence 670
analysing sentence 671
analysing sentence 672
analysing sentence 673
analysing sentence 674
analysing sentence 675
analysing sentence 676
analysing sentence 677
analysing sentence 678
analysing sentence 679
analysing sentence 680
analysing sentence 681
analysing sentence 682
analysing sentence 683
analysing sentence 684
analysing sentence 685
analysing sentence 686
analysing sentence 687
analysing sentence 688
analysing sentence 689
analysing sentence 690
analysing sentence 691
analysing sentence 692
analysing sentence 693
analysing sentence 694
analysing sentence 695
analysing sentence 696
analysing sentence 697
analysing sentence 698
analysing sentence 699
analysing sentence 700
analysing sentence 701
analysing sentence 702
analysing sentence 703
analysing sentence 704
analysing sentence 705
analysing sentence 706
analysing sentence 707
analysing sentence 708
analysing sentence 709
analysing sentence 710
analysing sentence 711
analysing sentence 712
analysing sentence 713
analysing sentence 714
analysing sentence 715
analysing sentence 716
analysing sentence 717
analysing sentence 718
analysing sentence 719
analysing sentence 720
analysing sentence 721
analysing sentence 722
analysing sentence 723
analysing sentence 724
analysing sentence 725
analysing sentence 726
analysing sentence 727
analysing sentence 728
analysing sentence 729
analysing sentence 730
analysing sentence 731
analysing sentence 732
analysing sentence 733
analysing sentence 734
analysing sentence 735
analysing sentence 736
analysing sentence 737
analysing sentence 738
analysing sentence 739
analysing sentence 740
analysing sentence 741
analysing sentence 742
analysing sentence 743
analysing sentence 744
analysing sentence 745
analysing sentence 746
analysing sentence 747
analysing sentence 748
analysing sentence 749
analysing sentence 750
analysing sentence 751
analysing sentence 752
analysing sentence 753
analysing sentence 754
analysing sentence 755
analysing sentence 756
analysing sentence 757
analysing sentence 758
analysing sentence 759
analysing sentence 760
analysing sentence 761
analysing sentence 762
analysing sentence 763
analysing sentence 764
analysing sentence 765
analysing sentence 766
analysing sentence 767
analysing sentence 768
analysing sentence 769
analysing sentence 770
analysing sentence 771
analysing sentence 772
analysing sentence 773
analysing sentence 774
analysing sentence 775
analysing sentence 776
analysing sentence 777
analysing sentence 778
analysing sentence 779
analysing sentence 780
analysing sentence 781
analysing sentence 782
analysing sentence 783
analysing sentence 784
analysing sentence 785
analysing sentence 786
analysing sentence 787
analysing sentence 788
analysing sentence 789
analysing sentence 790
analysing sentence 791
analysing sentence 792
analysing sentence 793
analysing sentence 794
analysing sentence 795
analysing sentence 796
analysing sentence 797
analysing sentence 798
analysing sentence 799
analysing sentence 800
analysing sentence 801
analysing sentence 802
analysing sentence 803
analysing sentence 804
analysing sentence 805
analysing sentence 806
analysing sentence 807
analysing sentence 808
analysing sentence 809
analysing sentence 810
analysing sentence 811
analysing sentence 812
analysing sentence 813
analysing sentence 814
analysing sentence 815
analysing sentence 816
analysing sentence 817
analysing sentence 818
analysing sentence 819
analysing sentence 820
analysing sentence 821
analysing sentence 822
analysing sentence 823
analysing sentence 824
analysing sentence 825
analysing sentence 826
analysing sentence 827
analysing sentence 828
analysing sentence 829
analysing sentence 830
analysing sentence 831
analysing sentence 832
analysing sentence 833
analysing sentence 834
analysing sentence 835
analysing sentence 836
analysing sentence 837
analysing sentence 838
analysing sentence 839
analysing sentence 840
analysing sentence 841
analysing sentence 842
analysing sentence 843
analysing sentence 844
analysing sentence 845
analysing sentence 846
analysing sentence 847
analysing sentence 848
analysing sentence 849
analysing sentence 850
analysing sentence 851
analysing sentence 852
analysing sentence 853
analysing sentence 854
analysing sentence 855
analysing sentence 856
analysing sentence 857
analysing sentence 858
analysing sentence 859
analysing sentence 860
analysing sentence 861
analysing sentence 862
analysing sentence 863
analysing sentence 864
analysing sentence 865
analysing sentence 866
analysing sentence 867
analysing sentence 868
analysing sentence 869
analysing sentence 870
analysing sentence 871
analysing sentence 872
analysing sentence 873
analysing sentence 874

KeyboardInterrupt:

In [ ]:
subset["scores"] = sentence_scores

In [ ]:

# Create DataFrame with custom column names
scores_df = pd.DataFrame(sentence_scores, columns=['speech_id', 'sentence_position', 'Anti-Elitism', 'People-Centrism', 'Left-Wing Host-Ideology', 'Right-Wing Host-Ideology'])

In [ ]:
scores_df.to_csv("populist_scores_per_sentence.csv")

In [ ]:
all_data_combined = pd.merge(subset, scores_df, on=['speech_id', 'sentence_position'])

In [ ]:
all_data_combined.to_csv("all_data_combined.csv", index=False)

,speech_id,sentence_position,sentence,MPID,Date,Chair,Session,Period,Party,Name,scores,Anti-Elitism,People-Centrism,Left-Wing Host-Ideology,Right-Wing Host-Ideology
0,0,1,Herr Präsident!,17826,2022-01-14,False,12,20,['afd'],Albrecht Glaser,"[0, 1, 0.1335628777742386, 0.07978134602308273...",0.133563,0.079781,0.057177,0.071662
1,0,2,Meine sehr verehrten Damen und Herren!,17826,2022-01-14,False,12,20,['afd'],Albrecht Glaser,"[0, 2, 0.14240780472755432, 0.0802032798528671...",0.142408,0.080203,0.056765,0.067925
2,0,3,Mehr Fortschritt soll es im Lande geben.,17826,2022-01-14,False,12,20,['afd'],Albrecht Glaser,"[0, 3, 0.17971497774124146, 0.1364448815584182...",0.179715,0.136445,0.084267,0.174430
3,0,4,"Was ist das, und wie soll das gehen?",17826,2022-01-14,False,12,20,['afd'],Albrecht Glaser,"[0, 4, 0.12137646228075027, 0.0820993185043335...",0.121376,0.082099,0.059250,0.081766
4,1,1,"Sehr geehrter Herr Dr. Hahn, ich versichere, d...",17826,2022-01-28,False,15,20,['afd'],Albrecht Glaser,"[1, 1, 0.15323865413665771, 0.0973944216966629...",0.153239,0.097394,0.064412,0.088444
5,1,2,Ich stelle nur eine einzige Frage an Sie,17826,2022-01-28,False,15,20,['afd'],Albrecht Glaser,"[1, 2, 0.11689471453428268, 0.0686059892177581...",0.116895,0.068606,0.054694,0.067936
6,2,1,Herr Präsident!,17826,2022-04-08,False,29,20,['afd'],Albrecht Glaser,"[2, 1, 0.1335628777742386, 0.07978134602308273...",0.133563,0.079781,0.057177,0.071662
7,2,2,Meine Damen und Herren!,17826,2022-04-08,False,29,20,['afd'],Albrecht Glaser,"[2, 2, 0.14925704896450043, 0.0711181014776229...",0.149257,0.071118,0.064535,0.069349
8,2,3,Verehrter Herr Finanzminister!,17826,2022-04-08,False,29,20,['afd'],Albrecht Glaser,"[2, 3, 0.1510973572731018, 0.069115549325943, ...",0.151097,0.069116,0.062389,0.069242
9,3,1,Frau Präsidentin!,17826,2022-05-13,False,35,20,['afd'],Albrecht Glaser,"[3, 1, 0.1590043604373932, 0.0861503854393959,...",0.159004,0.086150,0.080210,0.072853
10,3,2,Meine Damen und Herren!,17826,2022-05-13,False,35,20,['afd'],Albrecht Glaser,"[3, 2, 0.14925704896450043, 0.0711181014776229...",0.149257,0.071118,0.064535,0.069349
11,3,3,"Ziel des CDU/CSU-Antrages ist es, die vorüberg...",17826,2022-05-13,False,35,20,['afd'],Albrecht Glaser,"[3, 3, 0.14787332713603973, 0.1203044801950454...",0.147873,0.120304,0.061092,0.074344
12,3,4,Interessanterweise fordert die CDU/CSU die Bun...,17826,2022-05-13,False,35,20,['afd'],Albrecht Glaser,"[3, 4, 0.14513124525547028, 0.0943429246544838...",0.145131,0.094343,0.047389,0.066069
13,4,1,Frau Präsidentin!,17826,2022-09-22,False,54,20,['afd'],Albrecht Glaser,"[4, 1, 0.1590043604373932, 0.0861503854393959,...",0.159004,0.086150,0.080210,0.072853
14,4,2,Meine Damen und Herren!,17826,2022-09-22,False,54,20,['afd'],Albrecht Glaser,"[4, 2, 0.14925704896450043, 0.0711181014776229...",0.149257,0.071118,0.064535,0.069349
15,4,3,Wir beraten einen Antrag der Fraktion Die Link...,17826,2022-09-22,False,54,20,['afd'],Albrecht Glaser,"[4, 3, 0.1782618761062622, 0.08841351419687271...",0.178262,0.088414,0.076153,0.077506
16,4,4,Das ist ein Steckenpferd der Linken.,17826,2022-09-22,False,54,20,['afd'],Albrecht Glaser,"[4, 4, 0.1361161470413208, 0.09203670173883438...",0.136116,0.092037,0.072509,0.106693
17,4,5,Im letzten Jahr haben Sie die Abschöpfung von ...,17826,2022-09-22,False,54,20,['afd'],Albrecht Glaser,"[4, 5, 0.17549845576286316, 0.0810854732990264...",0.175498,0.081085,0.048670,0.074727
18,5,1,Frau Präsidentin!,17826,2022-10-13,False,60,20,['afd'],Albrecht Glaser,"[5, 1, 0.1590043604373932, 0.0861503854393959,...",0.159004,0.086150,0.080210,0.072853
19,5,2,Meine Damen und Herren!,17826,2022-10-13,False,60,20,['afd'],Albrecht Glaser,"[5, 2, 0.14925704896450043, 0.0711181014776229...",0.149257,0.071118,0.064535,0.069349
20,5,3,Herr Bundeskanzler spricht von „haltlosen Scha...,17826,2022-10-13,False,60,20,['afd'],Albrecht Glaser,"[5, 3, 0.21377907693386078, 0.0760941505432128...",0.213779,0.076094,0.050826,0.079327
21,5,4,Im Kern geht es bei dem Cum-ex-Skandal um den ...,17826,2022-10-13,False,60,20,['afd'],Albrecht Glaser,"[5, 4, 0.18537165224552155, 0.1128563880920410...",0.185372,0.112856,0.074874,0.079621
22,5,5,Dabei ist mindestens ein hoher zweistelliger M...,17826,2022-10-13,False,60,20,['afd'],Albrecht Glaser,"[5, 5, 0.19818930327892303, 0.1295278817415237...",0.198189,0.129528,0.108332,0.115102
23,5,6,"Auch die Commerzbank, die WestLB, die HSH Nord...",17826,2022-10-13,False,60,20,['afd'],Albrecht Glaser,"[5, 6, 0.17520064115524292, 0.0747230648994445...",0.175201,0.074723,0.076666,0.083127
24,5,7,Die Staatsanwaltschaft in Köln ermittelt mit 1...,17826,2022-10-13,False,60,20,['afd'],Albrecht Glaser,"[5, 7, 0.13484883308410645, 0.1090397685766220...",0.134849,0.109040,0.064154,0.083933
25,5,8,Der Schwerpunkt der betrügerischen Manipulatio...,17826,2022-10-13,False,60,20,['afd'],Albrecht Glaser,"[5, 8, 0.17680098116397858, 0.1034458130598068...",0.176801,0.103446,0.074613,0.116107
26,5,9,"Ist ein Mitglied des Hauses anwesend, das sein...",17826,2022-10-13,False,60,20,['afd'],Albrecht Glaser,"[5, 9, 0.0993351861834526, 0.06642894446849823...",0.099335,0.066429,0.038452,0.051546
27,5,10,– Das ist erkennbar nicht der Fall.,17826,2022-10-13,False,60,20,['afd'],Albrecht Glaser,"[5, 10, 0.15839967131614685, 0.098273776471614...",0.158400,0.098274,0.054798,0.089898
28,5,11,Dann schliesse ich die Abstimmung und bitte di...,17826,2022-10-13,False,60,20,['afd'],Albrecht Glaser,"[5, 11, 0.100979745388031, 0.07565806806087494...",0.100980,0.075658,0.037019,0.041607
29,5,12,Das Ergebnis der namentlichen Abstimmung wird ...,17826,2022-10-13,False,60,20,['afd'],Albrecht Glaser,"[5, 12, 0.12357056885957718, 0.117436744272708...",0.123571,0.117437,0.072042,0.085861
30,5,13,"Nun haben Sie endlich das Wort, Herr Kollege M...",17826,2022-10-13,False,60,20,['afd'],Albrecht Glaser,"[5, 13, 0.14953015744686127, 0.113494791090488...",0.149530,0.113495,0.069356,0.083455
31,6,1,Frau Präsidentin!,17826,2022-10-21,False,64,20,['afd'],Albrecht Glaser,"[6, 1, 0.1590043604373932, 0.0861503854393959,...",0.159004,0.086150,0.080210,0.072853
32,6,2,Meine Damen und Herren!,17826,2022-10-21,False,64,20,['afd'],Albrecht Glaser,"[6, 2, 0.14925704896450043, 0.0711181014776229...",0.149257,0.071118,0.064535,0.069349
33,6,3,Diese Regierung hat das Energiegeschäft mit Ru...,17826,2022-10-21,False,64,20,['afd'],Albrecht Glaser,"[6, 3, 0.17035549879074097, 0.0814579427242279...",0.170355,0.081458,0.065569,0.079083
34,7,1,Frau Präsidentin!,17826,2022-12-01,False,73,20,['afd'],Albrecht Glaser,"[7, 1, 0.1590043604373932, 0.0861503854393959,...",0.159004,0.086150,0.080210,0.072853
35,7,2,Meine Damen und Herren!,17826,2022-12-01,False,73,20,['afd'],Albrecht Glaser,"[7, 2, 0.14925704896450043, 0.0711181014776229...",0.149257,0.071118,0.064535,0.069349
36,7,3,Die Erbschaft- und die Schenkungsteuer war imm...,17826,2022-12-01,False,73,20,['afd'],Albrecht Glaser,"[7, 3, 0.14091458916664124, 0.0905417054891586...",0.140915,0.090542,0.068124,0.090725
37,7,4,Sie knüpft nicht an eine erwerbswirtschaftlich...,17826,2022-12-01,False,73,20,['afd'],Albrecht Glaser,"[7, 4, 0.12343911081552505, 0.0982431545853614...",0.123439,0.098243,0.065194,0.091206
38,7,5,Sie stellt eine legalisierte Enteignung dar.,17826,2022-12-01,False,73,20,['afd'],Albrecht Glaser,"[7, 5, 0.11761132627725601, 0.0866492316126823...",0.117611,0.086649,0.061950,0.075369
39,8,1,Frau Präsidentin!,17826,2023-01-27,False,83,20,['afd'],Albrecht Glaser,"[8, 1, 0.1590043604373932, 0.0861503854393959,...",0.159004,0.086150,0.080210,0.072853
40,8,2,Meine Damen und Herren!,17826,2023-01-27,False,83,20,['afd'],Albrecht Glaser,"[8, 2, 0.14925704896450043, 0.0711181014776229...",0.149257,0.071118,0.064535,0.069349
41,8,3,Das Problem der unkontrollierten Grösse des De...,17826,2023-01-27,False,83,20,['afd'],Albrecht Glaser,"[8, 3, 0.14995646476745605, 0.1181371882557869...",0.149956,0.118137,0.079091,0.097885
42,8,4,Die Parteienstruktur der frühen Bundesrepublik...,17826,2023-01-27,False,83,20,['afd'],Albrecht Glaser,"[8, 4, 0.13005635142326355, 0.0941653624176979...",0.130056,0.094165,0.072999,0.077824
43,9,1,"Ja, gerne.",17826,2023-03-01,False,87,20,['afd'],Albrecht Glaser,"[9, 1, 0.13835106790065765, 0.0994086191058158...",0.138351,0.099409,0.076230,0.095819
44,9,2,– Da haben wir doch noch eine kleine kognitive...,17826,2023-03-01,False,87,20,['afd'],Albrecht Glaser,"[9, 2, 0.1682448387145996, 0.10355851799249649...",0.168245,0.103559,0.065383,0.108931
45,9,3,Das ist der entscheidende Punkt und nicht die ...,17826,2023-03-01,False,87,20,['afd'],Albrecht Glaser,"[9, 3, 0.13750869035720825, 0.1013054773211479...",0.137509,0.101305,0.068792,0.087966
46,9,4,Genau das ist der Inhalt dieser zitierten Ents...,17826,2023-03-01,False,87,20,['afd'],Albrecht Glaser,"[9, 4, 0.1154419407248497, 0.10276556760072708...",0.115442,0.102766,0.067478,0.079445
47,10,1,"Herzlichen Dank, Frau Präsidentin, für die Fre...",17826,2023-03-17,False,92,20,['afd'],Albrecht Glaser,"[10, 1, 0.12590190768241882, 0.068868152797222...",0.125902,0.068868,0.043001,0.058790
48,10,2,Ich mache es auch ganz kurz.,17826,2023-03-17,False,92,20,['afd'],Albrecht Glaser,"[10, 2, 0.11804451793432236, 0.116311982274055...",0.118045,0.116312,0.077452,0.100374
49,10,3,"– Verehrter Herr Kollege Frei, würden Sie mir ...",17826,2023-03-17,False,92,20,['afd'],Albrecht Glaser,"[10, 3, 0.11800713837146759, 0.123896650969982...",0.118007,0.123897,0.056695,0.078202